INSERT INTO `_drug` (`catagory`,`code`,`name`,`price`,`unit`,`unitf`,`prices`,`units`,`description`) VALUES
	 ('ANTIBIOTIC / ANTIVIRUS','1','ACYCLOVIR 200 MG.',4.0,'เม็ด','25','100','box','รับประทานครั้งละ 1 เม็ด ทุก 4 ชั่วโมง วันละ 5 ครั้ง '),
	 ('ANTIBIOTIC / ANTIVIRUS','2','ACYCLOVIR 400MG.',0.0,'เม็ด','70','0','box',' รับประทานครั้งละ 1 เม็ด ทุก 12 ชั่วโมง'),
	 ('ANTIBIOTIC / ANTIVIRUS','3','ACYCLOVIR 800 MG.',6.9,'เม็ด','35','240','box','รับประทานครั้งละ1 เม็ด ทุก 4 ชั่วโมง วันละ 5 ครั้ง '),
	 ('ANTIBIOTIC / ANTIVIRUS','4','AMOXYCILLIN 500 MG',1.7,'เม็ด','500','850','box','รับประทานครั้งละ 2 เม็ด วันละ 2 ครั้ง หลังอาหาร เช้า-เย็น'),
	 ('ANTIBIOTIC / ANTIVIRUS','5','AUMENTIN 375 MG',9.5,'เม็ด','50','471','box','รับประทานครั้งละ 1 เม็ด วันละ 2 ครั้ง หลังอาหาร เช้า-เย็น'),
	 ('ANTIBIOTIC / ANTIVIRUS','6','AUMENTIN 625 MG',14.3,'เม็ด','15','214','box','รับประทานครั้งละ 1 เม็ดวันละ 2 ครั้ง หลังอาหาร เช้า - เย็น'),
	 ('ANTIBIOTIC / ANTIVIRUS','7','AZITHROMYCIN',20.0,'เม็ด','6','120','box','รับประทานครั้งละ 1 เม็ดวันละ 2 ครั้ง ก่อนอาหาร เช้า - เย็น'),
	 ('ANTIBIOTIC / ANTIVIRUS','8','CLOXACILLIN',0.0,'เม็ด','500','0','box','รับประทานครั้งละ 1 เม็ด วันละ 4 ครั้งก่อนอาหาร เช้า- กลางวัน- เย็น- ก่อนนอน'),
	 ('ANTIBIOTIC / ANTIVIRUS','9','DICLOXACILLIN 250 MG',2.0,'เม็ด','500','1000','box','รับประทานครั้งละ1 เม็ด วันละ 4 ครั้ง ก่อนอาหาร เช้า- กลางวัน -เย็น- ก่อนนอน'),
	 ('ANTIBIOTIC / ANTIVIRUS','10','DOXYCYCLIN 100 MG',1.5,'เม็ด','500','750','box','รับประทานครั้งละ 1 เม็ด วันละ 2 ครั้ง หลังอาหาร เช้า -เย็น');
INSERT INTO `_drug` (`catagory`,`code`,`name`,`price`,`unit`,`unitf`,`prices`,`units`,`description`) VALUES
	 ('ANTIBIOTIC / ANTIVIRUS','11','NORFLOXACIN 400 MG',1.0,'เม็ด','500','500','box','รับประทานครั้งละ 1 เม็ดวันละ 2 ครั้ง หลังอาหาร เช้า - เย็น'),
	 ('ANTIBIOTIC / ANTIVIRUS','12','OFLOXACIN',3.0,'เม็ด','100','300','box','รับประทานครั้งละ 1 เม็ด วันละ 2 ครั้ง หลังอาหาร เช้า - เย็น'),
	 ('ANTIBIOTIC / ANTIVIRUS','13','ROXITHROMYCIN 150 MG',0.0,'เม็ด','100','0','box','รับประทานครั้งละ 1 เม็ดวันละ 2 ครั้ง ก่อนอาหาร เช้า - เย็น'),
	 ('ANTI - INFLAMMATORY','14','BRUFEN 400 MG',0.0,'เม็ด','250','0','box','รับประทานครั้งละ 1 เม็ด ทุก 6 ชั่วโมง เวลาปวด มีไข้'),
	 ('ANTI - INFLAMMATORY','15','DANZEN',0.9,'เม็ด','500','425','box','รับประทานครั้งละ1 เม็ด วันละ 3 ครั้ง หลังอาหาร เช้า- กลางวัน -เย็น'),
	 ('ANTI - INFLAMMATORY','16','DICLOFENAC 25 MG',0.5,'เม็ด','500','180','box','รับประทาน ครั้งละ1 เม็ด วันละ 3 ครั้ง หลังอาหารทันที เช้า - กลางวัน - เย็น'),
	 ('ANTI - INFLAMMATORY','17','MYDOCLAM',1.2,'เม็ด','500','600','box','รับประทาน ครั้งละ1 เม็ด วันละ 3 ครั้ง หลังอาหารทันที เช้า- กลางวัน- เย็น'),
	 ('ANTI - INFLAMMATORY','18','NORGESIC',4.3,'เม็ด','1000','421','box','รับประทาน ครั้งละ1 เม็ด วันละ 3 ครั้ง หลังอาหารทันที เช้า- กลางวัน- เย็น'),
	 ('ANALGESICS ','19','PARACETAMOL 500 MG',0.0,'เม็ด','1000','0','box','รับประทานครั้งละ 1-2 เม็ด ทุก 4-6 ชั่วโมง เวลาปวด มีไข้'),
	 ('ANALGESICS ','20','PONSTAND 500 MG',1.3,'เม็ด','100','126','box','รับประทาน ครั้งละ1 เม็ด ทุก 6 ชั่วโมง');
INSERT INTO `_drug` (`catagory`,`code`,`name`,`price`,`unit`,`unitf`,`prices`,`units`,`description`) VALUES
	 ('ANTI-SPASMODICS','21','BUSCOPAN',1.8,'เม็ด','500','900','box','รับประทาน ครั้งละ1 เม็ดวันละ 3 ครั้ง หลังอาหาร เช้า- กลางวัน -เย็น'),
	 ('ANTI-EMETIC','22','DOMPERIDONE 10 MG',0.0,'เม็ด','250','0','box','รับประทาน ครั้งละ1 เม็ดวันละ 3 ครั้ง ก่อนอาหาร เช้า- กลางวัน- เย็น'),
	 ('ANTI-EMETIC','23','DIMENHYDRINATE 50 MG',0.3,'เม็ด','1000','234','box','รับประทาน ครั้งละ1 เม็ด วันละ 3 ครั้ง หลังอาหาร เช้า- กลางวัน- เย็น'),
	 ('GI & ANTACID DRUGS ','24',' ANTACIL TAB',0.0,'เม็ด','500','0','box','รับประทาน ครั้งละ1 เม็ด วันละ 3 ครั้ง หลังอาหาร เช้า- กลางวัน -เย็น (เคี้ยวก่อนกลืน)'),
	 ('GI & ANTACID DRUGS ','25',' BLOW - X',0.5,'เม็ด','500','238','box','รับประทาน ครั้งละ1 เม็ด วันละ 3 ครั้ง หลังอาหาร เช้า -กลางวัน- เย็น (เคี้ยวก่อนกลืน)'),
	 ('GI & ANTACID DRUGS ','26',' BISACODYL/SENOKOT',0.0,'เม็ด','0','0','box','รับประทาน ครั้งละ2-4 เม็ดวันละ 1 ครั้ง ก่อนนอน'),
	 ('GI & ANTACID DRUGS ','27','CA - R - BON ',2.9,'เม็ด','100','289','box','รับประทาน ครั้งละ2 เม็ดวันละ 3 ครั้ง หลังอาหาร เช้า -กลางวัน -เย็น'),
	 ('GI & ANTACID DRUGS ','28','MAGESTO',0.6,'เม็ด','100','60','box','รับประทาน ครั้งละ1 เม็ดวันละ 3 ครั้ง หลังอาหาร เช้า -กลางวัน- เย็น'),
	 ('GI & ANTACID DRUGS ','29','OMEPRAZOLE 20 MG',1.6,'เม็ด','350','550','box','รับประทานครั้งละ 1 เม็ด วันละ 1 ครั้ง ก่อนอาหาร เช้า'),
	 ('GI & ANTACID DRUGS ','30','RANITIDINE ',0.8,'เม็ด','1000','720','box','รับประทานครั้งละ 1 เม็ด วันละ 2 ครั้ง หลังอาหาร เช้า- เย็น');
INSERT INTO `_drug` (`catagory`,`code`,`name`,`price`,`unit`,`unitf`,`prices`,`units`,`description`) VALUES
	 ('ANTI - HISTAMINE','31',' ATARAX 10 MG',0.0,'เม็ด','500','0','box','รับประทาน ครั้งละ1 เม็ดวันละ 3 ครั้ง หลังอาหาร เช้า- กลางวัน- เย็น'),
	 ('ANTI - HISTAMINE','32',' CPM 4 MG',0.0,'เม็ด','0','0','box','รับประทาน ครั้งละ1 เม็ดวันละ 3 ครั้ง หลังอาหาร เช้า- กลางวัน- เย็น'),
	 ('ANTI - HISTAMINE','33',' CETIRIZINE 10 MG',0.9,'เม็ด','500','421','box','รับประทาน ครั้งละ1 เม็ดวันละ 1 ครั้ง หลังอาหาร ก่อนนอน'),
	 ('ANTI - HISTAMINE','34',' LORATADINE 10 MG',1.2,'เม็ด','250','281','box','รับประทานครั้งละ 1 เม็ด วันละ 1 ครั้ง ก่อนนอน'),
	 ('COUGH / COLD REMEDIES','35','BISOLVON ',0.3,'เม็ด','500','141','box','รับประทาน ครั้งละ1 เม็ดวันละ 3 ครั้ง หลังอาหาร เช้า- กลางวัน -เย็น'),
	 ('COUGH / COLD REMEDIES','36','DEXTROMETHORPHAN',0.9,'เม็ด','500','440','box','รับประทาน ครั้งละ1 เม็ดวันละ 3 ครั้ง หลังอาหาร เช้า- กลางวัน- เย็น'),
	 ('COUGH / COLD REMEDIES','37','THROATSIL/MYBACIN',8.1,'ซอง','40','321','box','อม ครั้งละ 1 เม็ด ทุก 1-2 ชั่วโมง เวลาเจ็บคอ'),
	 ('COUGH / COLD REMEDIES','38','MYSOVEN',0.0,'ซอง','60','0','box','ชงรับประทาน 1 ซองผสมน้ำครึ่งแก้ว 100 ซีซี'),
	 ('CEREBRAL ACTIVATOR','39','CINNARIZINE 25 MG',0.8,'เม็ด','50','38','box','รับประทาน ครั้งละ1 เม็ดวันละ 3 ครั้ง หลังอาหาร เช้า -กลางวัน- เย็น'),
	 ('CEREBRAL ACTIVATOR','40','FLUNARIZINE ',1.6,'เม็ด','50','76','pot','รับประทาน ครั้งละ1 เม็ดวันละ 1 ครั้ง ก่อนนอน');
INSERT INTO `_drug` (`catagory`,`code`,`name`,`price`,`unit`,`unitf`,`prices`,`units`,`description`) VALUES
	 ('ANTT ARRHYTHMICS','41',' PROPANOLOL 10 MG',0.0,'box','0','0','box',''),
	 ('CORTICOSTEROID','42','PREDNISOLONE 5 MG',0.0,'หลอด','0','0','pot',''),
	 ('PHYCHOSIS DRUGS','43','ALPRAZOLAM 0.25 MG',0.0,'box','0','0','box',''),
	 ('PHYCHOSIS DRUGS','44','ALPRAZOLAM 0.50 MG',0.0,'box','0','0','box',''),
	 ('PHYCHOSIS DRUGS','45','AMITRIPTYLINE 10 MG',0.0,'box','0','0','box',''),
	 ('PHYCHOSIS DRUGS','46','AMITRIPTYLINE 25 MG',0.4,'box','500','188','box',''),
	 ('PHYCHOSIS DRUGS','47','ATIVAN 0.50 MG',0.0,'box','0','0','box',''),
	 ('PHYCHOSIS DRUGS','48','ATIVAN 1 MG',0.0,'box','0','0','box',''),
	 ('PHYCHOSIS DRUGS','49','DIAZEPAM 2 MG',0.0,'เม็ด','0','0','pot500',''),
	 ('PHYCHOSIS DRUGS','50','DIAZEPAM 5 MG',0.0,'เม็ด','0','0','pot1000','');
INSERT INTO `_drug` (`catagory`,`code`,`name`,`price`,`unit`,`unitf`,`prices`,`units`,`description`) VALUES
	 ('PHYCHOSIS DRUGS','51','FLUOXETINE 20 MG',0.0,'box','0','0','box',''),
	 ('PHYCHOSIS DRUGS','52','HAROPERIDOL 2 MG',0.0,'เม็ด','0','0','pot1000',''),
	 ('PHYCHOSIS DRUGS','53','HAROPERIDOL 5 MG',0.0,'เม็ด','0','0','pot1000',''),
	 ('VITAMINS & MINERALS','54','MULTIVITAMIN',2.5,'เม็ด','500','200','box','รับประทาน วันละ 1 เม็ด พร้อมมื้ออาหาร'),
	 ('VITAMINS & MINERALS','55','ORS ',3.1,'ซอง','50','155','box','1 ซอง ละลายน้ำ 1 แก้ว 200 ซีซี'),
	 ('VITAMINS & MINERALS','56',' VITAMIN B2',0.0,'เม็ด','0','0','pot1000',''),
	 ('VITAMINS & MINERALS','57',' VITAMIN B1 - 6 - 12',0.5,'เม็ด','500','234','box','รับประทาน ครั้งละ1 เม็ดวันละ 3 ครั้ง หลังอาหาร เช้า -กลางวัน- เย็น'),
	 ('VITAMINS & MINERALS','58',' VITAMIN B COMPLEX',0.3,'เม็ด','50','200','box','รับประทานครั้งละ 1 เม็ด วันละ 2 ครั้ง หลังอาหาร เช้า -เย็น'),
	 ('VITAMINS & MINERALS','59',' VITAMIN C 25 MG',0.0,'ซอง','50','0','box','อม'),
	 ('VITAMINS & MINERALS','60',' VITAMIN C 50 MG',0.0,'ซอง','0','0','box','อม');
INSERT INTO `_drug` (`catagory`,`code`,`name`,`price`,`unit`,`unitf`,`prices`,`units`,`description`) VALUES
	 ('VITAMINS & MINERALS','61',' VITAMIN C 500 MG',0.0,'เม็ด','0','0','box','รับประทานครั้งละ 1 เม็ด วันละ 2 ครั้ง หลังอาหารทันที เช้า -เย็น'),
	 ('SUSPENSION','62','ANTACIL GEL',0.0,'ขวด','0','0','doz','รับประทาน ครั้งละ1 ช้อนโต๊ะวันละ 4 ครั้ง หลังอาหาร เช้า- กลางวัน- เย็น-ก่อนนอน'),
	 ('SUSPENSION','63',' M. CARMINATIVE',0.0,'ขวด','20','0','doz','รับประทาน ครั้งละ 1 ช้อนโต๊ะ วันละ 4 ครั้ง หลังอาหาร เช้า-กลางวัน-เย็น-ก่อนนอน'),
	 ('SUSPENSION','64',' M. SALOL ET MENTHOL 50 ML',10.0,'ขวด','12','115','doz','รับประทาน ครั้งละ1 ช้อนโต๊ะวันละ 4 ครั้ง หลังอาหาร เช้า- กลางวัน- เย็น-ก่อนนอน'),
	 ('SUSPENSION','65',' M. TUSSIS',0.0,'ขวด','0','0','box50',''),
	 ('SUSPENSION','66',' M. STOMACHICA',0.0,'ขวด','0','0','box20',''),
	 ('EYE - EAR','67','CHLORAM EYE DROP',14.0,'ขวด','12','168','doz','หยอดตา ครั้งละ 1-2 หยด วันละ 3 ครั้ง เช้า-กลางวัน-เย็น'),
	 ('EYE - EAR','68','CHLORAM EYE OINT ',0.0,'ขวด','0','0','doz',''),
	 ('EYE - EAR','69','DEXA - OPH EYE DROP',20.0,'ขวด','12','240','doz','หยอดตา ครั้งละ 1-2 หยด วันละ 4-6 ครั้ง'),
	 ('EYE - EAR','70','EAR-WAX ',0.0,'ขวด','0','0','doz','');
INSERT INTO `_drug` (`catagory`,`code`,`name`,`price`,`unit`,`unitf`,`prices`,`units`,`description`) VALUES
	 ('EYE - EAR','71','HISTA - OPH EYE DROP',15.0,'ขวด','12','180','doz','หยอดตา ครั้งละ 1-2 หยด วันละ 4-6 ครั้ง'),
	 ('EYE - EAR','72',' LAC - OPH ',0.0,'ขวด','0','0','box','หยอดตา ครั้งละ 1-2 หยด วันละ 3-4 ครั้ง เมื่อมีอาการ'),
	 ('EYE - EAR','73','OPSA',20.0,'ขวด','12','239','doz','ล้างตา วันละ 1-2 ครั้ง'),
	 ('EYE - EAR','74','TERAMYCIN EYE OINT',0.0,'หลอด','0','0','tube',''),
	 ('MOUTH','75','KENALOG IN ORABASE ',0.0,'ซอง','0','0','box','ป้ายแผลในปาก วันละ 4 ครั้ง เช้า-กลางวัน-เย็น-ก่อนนอน'),
	 ('SKIN - EXTERNAL APPLY','76','ACYCLOVIR CREAM',0.0,'หลอด','12','0','doz','ทาบางๆเฉพาะที่ 2 ครั้ง เช้าเย็น'),
	 ('SKIN - EXTERNAL APPLY','77','ALOVELA GEL',0.0,'หลอด','10','0','tube10','ทาบางๆเฉพาะที่ 2 ครั้ง เช้า-เย็น'),
	 ('SKIN - EXTERNAL APPLY','78','ANTI-BIOTIC CREAM',0.0,'หลอด','12','0','tube/10','ทาบางๆเฉพาะที่ 2 ครั้ง เช้า-เย็น'),
	 ('SKIN - EXTERNAL APPLY','79','ANALGESIC CREAM',0.0,'หลอด','12','0','tube/10','ทาบางๆเฉพาะที่ '),
	 ('SKIN - EXTERNAL APPLY','80','ANTI-FUNGUS CREAM',0.0,'หลอด','12','0','tube/10','ทาบางๆเฉพาะที่ 2 ครั้ง เช้า-เย็น');
INSERT INTO `_drug` (`catagory`,`code`,`name`,`price`,`unit`,`unitf`,`prices`,`units`,`description`) VALUES
	 ('SKIN - EXTERNAL APPLY','81','HAND GEL 60 ML',0.0,'หลอด','12','0','doz',''),
	 ('SKIN - EXTERNAL APPLY','82','HAND GEL 500 ML',0.0,'ขวด','1','0','bott',''),
	 ('SKIN - EXTERNAL APPLY','83',' 0.1 % TA CREAM',0.0,'หลอด','12','0','doz','ทาบางๆเฉพาะที่ 2 ครั้ง เช้า-เย็น'),
	 ('SKIN - EXTERNAL APPLY','84',' 0.02 % TA CREAM',0.0,'หลอด','12','0','doz','ทาบางๆเฉพาะที่ 2 ครั้ง เช้า-เย็น'),
	 ('SKIN - EXTERNAL APPLY','85','TA LOTION',0.0,'ขวด','12','0','doz','ทาบางๆเฉพาะที่ 2 ครั้ง เช้า-เย็น'),
	 ('SKIN - EXTERNAL APPLY','86','WHITFIELD OINT.',0.0,'หลอด','0','0','box',''),
	 ('SKIN - EXTERNAL APPLY','87','VOLTA GEL',0.0,'หลอด','12','0','doz','ทาบางๆเฉพาะที่ '),
	 ('SKIN - EXTERNAL APPLY','88','ขี้ผึ้งแก้ปวดบวม 15 กรัม',0.0,'หลอด','0','0','tube/10','ทาบางๆเฉพาะที่ '),
	 ('SKIN - EXTERNAL APPLY','89','SKETOLENE',0.0,'ขวด','12','0','doz','ฉีดพ่นบริเวณผิวหนัง'),
	 ('SOLUTION','90','ALCOHOL 70% 60 ML.',0.0,'ขวด','50','0','bott','');
INSERT INTO `_drug` (`catagory`,`code`,`name`,`price`,`unit`,`unitf`,`prices`,`units`,`description`) VALUES
	 ('SOLUTION','91','ALCOHOL 70% 240ML.',0.0,'ขวด','0','0','bott',''),
	 ('SOLUTION','92','ALCOHOL 70% 450 ML',0.0,'ขวด','0','0','bott',''),
	 ('SOLUTION','93','ALCOHOL PAD',1.9,'ชิ้น','100','187','box',''),
	 ('SOLUTION','94','BETADINE 15 ML',0.0,'ขวด','24','0','box24',''),
	 ('SOLUTION','95','BETADINE 500 ML',130.0,'ขวด','1','130','bott',''),
	 ('SOLUTION','96','BETADINE OINTMENT',550.0,'กระปุก','1','550','bott',''),
	 ('SOLUTION','97','BETADINE SCRUB',145.0,'ขวด','1','145','bott',''),
	 ('SOLUTION','98','CALAMINE LOTION 60 ML',0.0,'ขวด','12','0','doz',''),
	 ('SOLUTION','99','HYDROGEN PEROXIDE',25.8,'ขวด','1','25.8','bott',''),
	 ('SOLUTION','100','NSS IRRIGATION 100 ML',35.0,'ขวด','24','840','box24','');
INSERT INTO `_drug` (`catagory`,`code`,`name`,`price`,`unit`,`unitf`,`prices`,`units`,`description`) VALUES
	 ('SOLUTION','101','NSS IRRIGATION1000 ML',30.0,'ขวด','12','360','box12',''),
	 ('SOLUTION','102','SPIRIT AMMONIA 30 ML',0.0,'ขวด','0','0','box12',''),
	 ('SOLUTION','103','SPIRIT AMMONIA 450 ML',0.0,'ขวด','0','0','bott',''),
	 ('SOLUTION','104','พิมเสนน้ำ',0.0,'ขวด','0','0','box',''),
	 ('INJECTION','105','ADRENALINE',3.21,'amp','1','3.21','box50',''),
	 ('INJECTION','106','BUSCOPAN',4.5,'amp','1','4.5','box50',''),
	 ('INJECTION','107','CPM',2.24,'amp','1','2.24','box100',''),
	 ('INJECTION','108','5%DN/2 500 ML',62.0,'bott','10','620','bott',''),
	 ('INJECTION','109','50% GLUCOSE 20 ML',70.0,'amp','1','70','box',''),
	 ('INJECTION','110','0.9%NSS 1000 ML',0.0,'ขวด','1','0','bott','');
INSERT INTO `_drug` (`catagory`,`code`,`name`,`price`,`unit`,`unitf`,`prices`,`units`,`description`) VALUES
	 ('INJECTION','111','PLASIL',0.0,'amp','1','0','box50',''),
	 ('INJECTION','112','T.T.',0.0,'amp','1','0','box12',''),
	 ('','113','TA LONE LOTION',0.0,'ขวด','12','0','doz','ทาบางๆเฉพาะที่ 2 ครั้ง เช้า-เย็น'),
	 ('','114','LIDOCAINE 1%',0.0,'ขวด','1','0','bott30',''),
	 ('','115','OMEPLAZOLE INJ.',0.0,'vial','1','0','vial50',''),
	 ('','116','SALBUTAMAL INHALOR',0.0,'vial','0','0','piece2','พ่นเมื่อมีอาการ'),
	 ('','117','OPSACIN',18.8,'ขวด','12','225','doz',''),
	 ('','118','M. SALOL ET MENTHOL 200 ML',35.4,'ขวด','12','424','doz','รับประทาน ครั้งละ1 ช้อนโต๊ะวันละ 4 ครั้ง หลังอาหาร เช้า- กลางวัน- เย็น-ก่อนนอน'),
	 ('','119','MASK DISPOSIBLE',0.0,'','','','box','ผ้าปิดจมูก ปาก');
INSERT INTO `_drug` (`catagory`,`code`,`name`,`price`,`unit`,`unitf`,`prices`,`units`,`description`) VALUES
	 ('','120','TA LONE LOTION',0.0,'ขวด','','','doz','ทาบางๆเฉพาะที่ 2 ครั้ง เช้า-เย็น'),
	 ('','121','GLOVE L disposible',0.0,'','','','box',''),
	 ('','122','PREG TESE',0.0,'','','','pack',''),
	 ('','123','NEEDLE NO.25',0.0,'','','','box',''),
	 ('','124','LIDOCAINE 1 %',0.0,'ขวด','','','bottle',''),
	 ('','125','OMEPLAZOLE INJ.',0.0,'amp','','','vial',''),
	 ('','126','NSS IRRIGATION 500 ML',50.0,'bott','1','50','bottle',''),
	 ('','127','SULBUTAMAL INHALOR',0.0,'vail','','','',''),
	 ('','128','OPSACIN',0.0,'ขวด','','','doz','');
INSERT INTO `_drug` (`catagory`,`code`,`name`,`price`,`unit`,`unitf`,`prices`,`units`,`description`) VALUES
	 ('','134','AUGMANTIN 1000 MG.',0.0,'เม็ด','','','box',''),
	 ('','129','PLASTER PLASTIC',0.0,'ชิ้น','100','','box','ปิดแผล'),
	 ('','130','PLASTER ผ้า',0.0,'ชิ้น','100','','box','ปิดแผล'),
	 ('','135','ยาอมมะแว้ง',0.0,'ซอง','','','','อม ครั้งละ 1 เม็ด ทุก 1-2 ชั่วโมง เวลาเจ็บคอ'),
	 ('','136','POLY OPH EYE DROP',0.0,'','','','',''),
	 ('','137','M SALOL ET MENTAL 200 ML',0.0,'ขวด','','','dozen','รับประทานครั้งละ 1 ช้อนโต๊ะ วันละ 4 ครั้ง หลังอาหาร เช้า กลางวัน เย็น ก่อนนอน'),
	 ('','138','ครีมไพล สูตรร้อน',0.0,'หลอด','','','หลอด','ทาบริเวณที่ปวด วันละ 2 ครั้ง เช้า-เย็น'),
	 ('','139','Clotrimazole Cr. 1%',0.0,'','','','หลอด','ทาบางๆบริเวณที่เป็น วันละ2ครั้ง เช้า-เย็น');
INSERT INTO `_drug` (`catagory`,`code`,`name`,`price`,`unit`,`unitf`,`prices`,`units`,`description`) VALUES
	 ('','140','ฟ้าทะลายโจร',0.0,'','','','','ครั้งละ 3 เม็ด วันละ 3 เวลาหลังอาหาร ติดต่อไม่เกิน 3 วัน');
INSERT INTO `_fac` (`name`,`code`) VALUES
	 ('คณะนิติศาสตร์',''),
	 ('วิทยาลัยสหวิทยาการและสถาบันศึกษาความร่วมมือระหว่างประเทศแห่งมธ.',''),
	 ('คณะวิทยาศาสตร์และเทคโนโลยี และสถาบันเทคโนโลยีนานาชาติสิรินธร',''),
	 ('คณะนิติศาสตร์และคณะเศรษฐศาสตร์',''),
	 ('วิทยาลัยแพทยศาสตร์นานาชาติจุฬาภรณ์',''),
	 ('วิทยาลัยโลกคดีศึกษา',''),
	 ('วิทยาลัยนานาชาติปรีดี พนมยงค์',''),
	 ('วิทยาลัยสหวิทยาการ',''),
	 ('วิทยาลัยนวัตกรรม',''),
	 ('สถาบันเทคโนโลยีนานาชาติสิรินธร','');
INSERT INTO `_fac` (`name`,`code`) VALUES
	 ('สถาบันภาษา',''),
	 ('คณะวิทยาการเรียนรู้และศึกษาศาสตร์',''),
	 ('คณะเภสัชศาสตร์',''),
	 ('คณะสาธารณสุขศาสตร์',''),
	 ('คณะสถาปัตยกรรมศาสตร์และการผังเมือง',''),
	 ('คณะศิลปกรรมศาสตร์',''),
	 ('คณะพยาบาลศาสตร์',''),
	 ('คณะทันตแพทยศาสตร์',''),
	 ('คณะสหเวชศาสตร์',''),
	 ('คณะแพทยศาสตร์','');
INSERT INTO `_fac` (`name`,`code`) VALUES
	 ('คณะวิศวกรรมศาสตร์',''),
	 ('คณะวิทยาศาสตร์และเทคโนโลยี',''),
	 ('คณะสังคมวิทยาและมานุษยวิทยา',''),
	 ('คณะวารสารศาสตร์และสื่อสารมวลชน',''),
	 ('คณะศิลปศาสตร์',''),
	 ('คณะสังคมสงเคราะห์ศาสตร์',''),
	 ('คณะเศรษฐศาสตร์',''),
	 ('คณะรัฐศาสตร์',''),
	 ('คณะพาณิชยศาสตร์และการบัญชี',''),
	 ('สำนักบัณฑิตอาสาสมัคร','');
INSERT INTO `_fac` (`name`,`code`) VALUES
	 ('วิทยาลัยพัฒนศาสตร์ ป๋วย อึ๊งภากรณ์','');
INSERT INTO `_hos` (`name`) VALUES
	 ('ร.พ.เกษมราษฎร์ (บางแค)'),
	 ('ร.พ.เกษมราษฎร์ ประชาชื่น'),
	 ('ร.พ.เจ้าพระยา'),
	 ('ร.พ.เซนต์หลุยส์'),
	 ('ร.พ.เซ็นทรัลเยนเนอรัล'),
	 ('ร.พ.เดชา'),
	 ('ร.พ.เทพธารินทร์'),
	 ('ร.พ.เปาโล เมโมเรียล โชคชัย 4'),
	 ('ร.พ.เปาโลเมโมเรียล'),
	 ('ร.พ.เพชรเวช');
INSERT INTO `_hos` (`name`) VALUES
	 ('ร.พ.เมโย'),
	 ('ร.พ.เวชธานี'),
	 ('ร.พ.เสรีรักษ์'),
	 ('ร.พ.แพทย์ปัญญา'),
	 ('ร.พ.ไทยนครินทร์'),
	 ('ร.พ.กรุงเทพ'),
	 ('ร.พ.กรุงเทพคริสเตียน'),
	 ('ร.พ.กล้วยน้ำไท 1'),
	 ('ร.พ.กล้วยน้ำไท 2'),
	 ('ร.พ.การุญเวช สุขาภิบาล 3');
INSERT INTO `_hos` (`name`) VALUES
	 ('ร.พ.คามิลเลียน'),
	 ('ร.พ.จุฬารัตน์ 7'),
	 ('ร.พ.จุฬารัตน์ 8'),
	 ('ร.พ.ธนบุรี 1'),
	 ('ร.พ.ธนบุรี 2'),
	 ('ร.พ.นครธน'),
	 ('ร.พ.นวมินทร์ 9'),
	 ('ร.พ.นวมินทร์'),
	 ('ร.พ.บางโพ'),
	 ('ร.พ.บางไผ่');
INSERT INTO `_hos` (`name`) VALUES
	 ('ร.พ.บางกอกเนอสซิ่งโฮม (BNH)'),
	 ('ร.พ.บางนา 1'),
	 ('ร.พ.บางปะกอก 1'),
	 ('ร.พ.บางปะกอก 8'),
	 ('ร.พ.บางปะกอก 9 อินเตอร์เนชั่นแนล'),
	 ('ร.พ.บำรุงราษฎร์'),
	 ('ร.พ.บี.แคร์.เมดิคอลเซ็นเตอร์'),
	 ('ร.พ.ประชาพัฒน์ (เดิม รพ.นวมินทร์ 2)'),
	 ('ร.พ.ปิยะเวท'),
	 ('ร.พ.พญาไท 1');
INSERT INTO `_hos` (`name`) VALUES
	 ('ร.พ.พญาไท 2'),
	 ('ร.พ.พญาไท 3'),
	 ('ร.พ.พญาไท นวมินทร์ (ร.พ.เปาโลฯ นวมินทร์)'),
	 ('ร.พ.พร้อมมิตร'),
	 ('ร.พ.พระรามเก้า'),
	 ('ร.พ.มเหสักข์'),
	 ('ร.พ.มงกุฎวัฒนะ'),
	 ('ร.พ.มิชชั่น'),
	 ('ร.พ.ยันฮี'),
	 ('ร.พ.รามคำแหง');
INSERT INTO `_hos` (`name`) VALUES
	 ('ร.พ.ราษฎร์บูรณะ'),
	 ('ร.พ.ลาดพร้าว'),
	 ('ร.พ.วิชัยเวช อินเตอร์เนชั่นแนล หนองแขม'),
	 ('ร.พ.วิภาราม'),
	 ('ร.พ.วิภาวดี 1'),
	 ('ร.พ.ศรีวิชัย 1'),
	 ('ร.พ.ศิครินทร์'),
	 ('ร.พ.ศิริราช  รับเฉพาะกรณีผู้ป่วยใน'),
	 ('ร.พ.ศิริราช ปิยมหาราชการุณย์'),
	 ('ร.พ.สมิติเวช (ศรีนครินทร์)');
INSERT INTO `_hos` (`name`) VALUES
	 ('ร.พ.สมิติเวช (สุขุมวิท)'),
	 ('ร.พ.สมิติเวช ธนบุรี'),
	 ('ร.พ.สายไหม'),
	 ('ร.พ.สินแพทย์'),
	 ('ร.พ.สุขุมวิท'),
	 ('ร.พ.หัวเฉียว');
INSERT INTO `_icd10` (`code`,`name_th`,`name_en`) VALUES
	 ('L029','ฝี ตุ่มหนอง','Cutaneous abscess, furuncle and carbuncle, unspecified'),
	 ('L709','สิว','Acne, unspecified'),
	 ('R104','ปวดท้อง','Abdominal pain, unspecified'),
	 ('A099','ท้องเสีย  ','Gastroenteritis and colitis of unspecified origin '),
	 ('K120','แผลในปาก','Recurrent oral aphthae, unspecified'),
	 ('X2999','สัมผัสพิษสัตว์หรือพืชมีพิษอื่น','Contact with unspecified venomous animal or plant at unspecified place During unspecified activity'),
	 ('X1299','น้ำร้อนลวก สัมผัสของเหลวร้อนอื่น','Contact with hot drinks, food, fats and cooking oils at unspecified place During unspecified activity'),
	 ('L039','เนื้อเยื่ออักเสบ','Cellulitis, unspecified'),
	 ('Z000','การตรวจสุขภาพร่างกายทั่วไป ( ประจำปี )','General medical examination'),
	 ('H109','เยื่อบุตาอักเสบ','Conjunctivitis, unspecified');
INSERT INTO `_icd10` (`code`,`name_th`,`name_en`) VALUES
	 ('R42','เวียนศีรษะ มึนงง','Dizziness and giddiness'),
	 ('W5499','สุนัขกัด','Bitten or struck by dog at unspecified place During unspecified activity'),
	 ('N946','ปวดท้องประจำเดือน','Dysmenorrhoea, unspecified'),
	 ('R040','เลือดกำเดาไหล','Epistaxis'),
	 ('H571','ปวดตา','Ocular pain'),
	 ('R53','อ่อนเพลีย','Malaise and fatigue'),
	 ('R509','ไข้ ไม่ทราบสาเหตุ','Fever, unspecified'),
	 ('J111','ไข้หวัดใหญ่','Influenza with other respiratory manifestations,virus not identified'),
	 ('R510','ปวดศีรษะ','Headache, unspecified'),
	 ('I849','ริดสีดวง','Unspecified haemorrhoids without complication');
INSERT INTO `_icd10` (`code`,`name_th`,`name_en`) VALUES
	 ('B029','งูสวัด','Zoster without complication'),
	 ('B009','เริม ','Herpesviral infection, unspecified'),
	 ('H000','ตากุ้งยิง','Hordeolum and other inflammation of eyelid'),
	 ('I959','ความดันโลหิตต่ำ','Hypotension, unspecified'),
	 ('M545','ปวดเอว','Low back pain Site unspecified'),
	 ('V2849','ขับมอเตอร์ไซด์ล้ม','Motorcycle rider injured in noncollision transport accident at driver injured in traffic accident During unspecified activity'),
	 ('G439','ไมเกรน','Migraine, unspecified'),
	 ('M791','ปวดกล้ามเนื้อ','Myalgia'),
	 ('L600','เล็บขบ','Ingrowing nail'),
	 ('M170','ข้อเข่าเสื่อม','Primary gonarthrosis,  bilateral');
INSERT INTO `_icd10` (`code`,`name_th`,`name_en`) VALUES
	 ('J069','ติดเชื้อทางเดินหายใจส่วนบน','Acute upper respiratory infection, unspecified'),
	 ('Z480','ทำแผล ตัดไหม','Attention to surgical dressings and sutures'),
	 ('H110','ต้อเนื้อ','Pteygium'),
	 ('K279','โรคกระเพาะ','Peptic ulcer, site unspecified Unspecified as acute or chronic, without haemorrhage or perforation'),
	 ('R55','เป็นลม','Syncope and collapse'),
	 ('E059',' ไทรอยด์เป็นพิษ','Thyrotoxicosis, unspecified'),
	 ('K088','ปวดฟัน','Toothache'),
	 ('L509','ผื่นแพ้','Urticaria, unspecified'),
	 ('N390','ทางเดินปัสสาวะอักเสบ','Urinary tract infection, site not specified'),
	 ('B349','ติดเชื้อไวรัส','Viral infection, unpecified');
INSERT INTO `_icd10` (`code`,`name_th`,`name_en`) VALUES
	 ('W2699','มีดบาด','Contact with knife, sword or dagger at unspecified place During unspecified activity'),
	 ('V1849','ถีบจักรยานล้มเอง','Pedal cyclist injured in noncollision transport accident at driver injured in traffic accident During unspecified activity'),
	 ('W0199','พลัด ตก ลื่นล้ม','Fall on same level from slipping, tripping and stumbling at unspecified place During unspecified activity'),
	 ('W2199','อุปกรณ์กีฬาชน กระแทก','Striking against or struck by sports equipment at unspecified place During unspecified activity'),
	 ('F329','ซึมเศร้า','Depressive epsiode, unspecified'),
	 ('F453','เครียด Hyperventilation','Somatization disorder,Respiratory system'),
	 ('W5399','หนูกัด','Bitten by rat at unspecified place During unspecified activity'),
	 ('V4859','ขับรถยนตร์พลิก คว่ำ','Car occupant injured in noncollision transport accident at driver injured in traffic accident During unspecified activity'),
	 ('V5859','ขับรถปิกอัพ พลิก คว่ำ','Occupant of pick-up truck or van injured in noncollision transport accident at driver injured in traffic  accident During unspecified activity'),
	 ('E149','เบาหวาน','Unspecified diabetes mellitus at without complications');
INSERT INTO `_icd10` (`code`,`name_th`,`name_en`) VALUES
	 ('F239','จิตเวช','Acute and transient psychotic disorder, unspecified'),
	 ('H920','ปวดหู','Otagia'),
	 ('I10','ความดันโลหิตสูง','Essential (primary) hypertension'),
	 ('J00','หวัด','Acute nasopharyngitis [common cold]'),
	 ('S009','ถลอก ฟก ช้ำ ของศีรษะ','Superficial injury of head, part unspecified'),
	 ('S019','แผลฉีกขาด ของศีรษะ','Open wound of head, part unspecified'),
	 ('S029','กระดูกแตกหักของ กระโหลกศีรษะ','Fracture of skull and facial bones, part unspecified'),
	 ('S109','ถลอก ฟก ช้ำ บริเวณคอ','Superficial injury of neck, part unspecified'),
	 ('S119','แผลฉีกขาด ที่คอ','Open wound of neck, part unspecified'),
	 ('S129','กระดูกแตกหักของ กระดูกคอ','Fracture of neck, part unspecified');
INSERT INTO `_icd10` (`code`,`name_th`,`name_en`) VALUES
	 ('S208','ถลอก ฟก ช้ำ บริเวณทรวงอก','Superficial injury of other and unspecified parts of thorax'),
	 ('S219','แผลฉีกขาด ที่ทรวงอก','Open wound of thorax, part unspecified'),
	 ('S229','กระดูกแตกหักของ กระดูกอกและซี่โครง','Fracture of bony thorax, part unspecified'),
	 ('S309','ถลอก ฟก ช้ำ บริเวณท้อง หลังส่วนล่าง เอว เชิงกราน','Superficial injuries of abdomen, lower back and pelvis, part unspecified'),
	 ('S318','แผลฉีกขาด ท้อง หลังส่วนล่าง เอว เชิงกราน','Open wound of other and unspecified parts of abdomen'),
	 ('S328','กระดูกแตกหักของ กระดูกสันหลังบริเวณเอว เชิงกราน','Fracture of other and unspecified parts of lumbar spine and pelvis'),
	 ('S409','ถลอก ฟก ช้ำ บริเวณหัวไหล่และต้นแขน','Superficial injury of shoulder and upper arm, unspecified'),
	 ('S418','แผลฉีกขาด หัวไหล่และต้นแขน','Open wound of other and unspecified parts of shoulder girdle'),
	 ('S429','กระดูกแตกหักของ กระดูกหัวไหล่และต้นแขน','โFracture of shoulder girdle, part unspecified'),
	 ('S437','ข้อและเอ็นบริเวณไหล่เคลื่อน เคล็ด ขัด ยอก','Sprain and strain of other and unspecified parts of shoulder girdle');
INSERT INTO `_icd10` (`code`,`name_th`,`name_en`) VALUES
	 ('S509','ถลอก ฟก ช้ำ บริเวณศอกและปลายแขน','Superficial injury of elbow and forearm, unspecified'),
	 ('S518','แผลฉีกขาด ศอกและปลายแขน','Open wound of other parts of forearm'),
	 ('S529','กระดูกแตกหักของ กระดูก ศอกและปลายแขน','Fracture of forearm, part unspecified'),
	 ('S534','ข้อและเอ็นบริเวณศอกและปลายแขน เคลื่อน เคล็ด ขัด ยอก','Sprain and strain of elbow'),
	 ('S609','ถลอก ฟก ช้ำ บริเวณข้อมือและมือ','Superficial injury of wrist and hand, unspecified'),
	 ('S619','แผลฉีกขาด ข้อมือและมือ','Open wound of wrist and hand, part unspecified'),
	 ('S628','กระดูกแตกหักของ กระดูกข้อมือและมือ','Fracture of other and unspecified parts of wrist and hand'),
	 ('S637','ข้อและเอ็นบริเวณข้อมือและมือ เคลื่อน เคล็ด ขัด ยอก','Sprain and strain of other and unspecified parts of hand'),
	 ('S709','ถลอก ฟก ช้ำ บริเวณสะโพกและต้นขา','Superficial injury of hip and thigh, unspecified'),
	 ('S718','แผลฉีกขาด สะโพกและต้นขา','Open wound of other and unspecified parts of pelvic girdle');
INSERT INTO `_icd10` (`code`,`name_th`,`name_en`) VALUES
	 ('S729','กระดูกแตกหักของ กระดูกสะโพกและต้นขา','Fracture of femur, part unspecified'),
	 ('S731','ข้อและเอ็นบริเวณสะโพกและต้นขา เคลื่อน เคล็ด ขัด ยอก','Sprain and strain of hip'),
	 ('S809','ถลอก ฟก ช้ำ บริเวณเข่าและปลายเท้า','Superficial injury of knee and leg, unspecified'),
	 ('S819','แผลฉีกขาด เข่าและปลายเท้า','Open wound of knee and leg, part unspecified'),
	 ('S829','กระดูกแตกหักของ กระดูกเข่าและปลายเท้า','Fracture of lower leg, part unspecified'),
	 ('S836','ข้อและเอ็นบริเวณเข่าและปลายเท้า เคลื่อน เคล็ด ขัด ยอก','Sprain and strain of other and unspecified parts of knee'),
	 ('S909','ถลอก ฟก ช้ำ บริเวณข้อเท้า และเท้า','Superficial injury of ankle and foot, unspecified'),
	 ('S919','แผลฉีกขาดข้อเท้า และเท้า','Open wound of ankle and foot, unspecified'),
	 ('S929','กระดูกแตกหักของ กระดูกข้อเท้า และเท้า','Fracture of foot, unspecified'),
	 ('S936','ข้อและเอ็นบริเวณข้อเท้า และเท้า เคลื่อน เคล็ด ขัด ยอก','Sprain and strain of other and unspecified parts of foot');
INSERT INTO `_icd10` (`code`,`name_th`,`name_en`) VALUES
	 ('T290','แผลถูกความร้อน หลายบริเวณ มีระบุความรุนแรง','Burns of multiple regions, unspecified degree'),
	 ('T634','ถูกพิษจากการสัมผัสสัตว์มีพิษ','Venom of other arthropods toxic effect'),
	 ('V0929','คนเดินเท้าบาดเจ็บในอุบัติเหตุจราจร','Pedestrian injured in traffic accident involving other and unspecified motor vehicles During unspecified activity'),
	 ('W1099','พลัด ตกบันได','Fall on and from stairs and steps at unspecified place During unspecified activity'),
	 ('W4499','วัตถุแปลกปลอมเข้าตา หู','Foreign body entering into or through eye or natural orifice at unspecified place During unspecified activity'),
	 ('W4599','วัตถุแปลกปลอม หนามตำ แทงผ่านทางผิวหนังเข้าไป','Foreign body or object entering through skin at unspecified place During unspecified activity'),
	 ('W5599','แมว สัตว์เลี้ยงลูกอื่นๆด้วยนมกัด','Bitten or struck by other mammals at unspecified place During unspecified activity'),
	 ('W7099','ตกน้ำและ จมน้ำ จากการพลัดตกหกล้ม','Drowning and submersion following fall into natural water at unspecified place During unspecified activity'),
	 ('W8599','ไฟช๊อต','Exposure to electric transmission lines at unspecified place During unspecified activity'),
	 ('X8499','ทำร้ายตัวเอง','Intentional self-harm by unspecified means at unspecified place During unspecified activity');
INSERT INTO `_icd10` (`code`,`name_th`,`name_en`) VALUES
	 ('Y0999','ถูกทำร้ายร่างกายโดยมิได้ระบุรายละเอี่ยดวิธี','Assault by unspecified means at unspecified place During unspecified activity'),
	 ('Z235','ฉีดวัคซีน บาดทะยัก','Need for immunization against tetanus alone'),
	 ('Z251','ฉีดวัคซีน ไข้หวัดใหญ่','Need for immunization against influenza'),
	 ('Z713','การให้คำปรึกษาและการเฝ้าระวังด้านโภชนาการ','Dietary counselling and surveillance'),
	 ('Z714','การให้คำปรึกษาและการเฝ้าระวังการติดสุรา','Alcohol abuse counselling and surveillance'),
	 ('Z715','การให้คำปรึกษาและการเฝ้าระวังการติดยา','Drug abuse counselling and surveillance'),
	 ('Z716','การให้คำปรึกษาและการเฝ้าระวังการติดบุหรี่','Tobacco abuse counselling'),
	 ('Z717','การให้คำปรึกษาเกี่ยวกับไวรัส HIV','Human immunodeficiency virus [HIV] counselling'),
	 ('Z719','การให้คำปรึกษาที่มิได้ระบุรายละเอียด','Counselling, unspecified'),
	 ('Z725','ปัญหาลักษณะการใช้ชีวิต พฤติกรรมเสี่ยงทางเพศ','High-risk sexual behaviour');
INSERT INTO `_icd10` (`code`,`name_th`,`name_en`) VALUES
	 ('A111102','อุบัติเหตุ','Accident'),
	 ('A111106','แพ้','Allergy'),
	 ('A111108','หอบหืด','Asthma'),
	 ('C111103','หนาวสั่น','Chill'),
	 ('C111104','แผลเรื้อรัง','Chronic Wound'),
	 ('C111105','ไข้หวัด','Common Cold'),
	 ('C111107','บาดแผลฟกช้ำ','Contussion Wound'),
	 ('C111108','ไอ','Cough'),
	 ('C111109','แผลจากของมีคม','Cut wound'),
	 ('C111110','กระเพาะปัสสาวะอักเสบ','Cystitis');
INSERT INTO `_icd10` (`code`,`name_th`,`name_en`) VALUES
	 ('D111101','ผิวหนังอักเสบ จากการแพ้','Dermatitis'),
	 ('D111102','ท้องเสีย','Diarrhea'),
	 ('D111103','เคลื่อนหลุด','Dislocate'),
	 ('D111107','อาหารไม่ย่อย','Dyspepsia'),
	 ('E111102','ระคายเคืองตา','Eye irritated'),
	 ('F111104','อาหารเป็นพิษ','Food poinsoning'),
	 ('F111105','สิ่งแปลกปลอมในร่างกาย','Foreing body'),
	 ('F111106','แตก หัก','Fracture'),
	 ('G111101','กระเพาะอาหารอักเสบ','Gastitis'),
	 ('H111102','มีเลือดคั่ง','Hematoma');
INSERT INTO `_icd10` (`code`,`name_th`,`name_en`) VALUES
	 ('H111107','ความดันโลหิตสูง','Hypertension'),
	 ('I111101','แผลติดเชื้อ','Infected wound'),
	 ('I111102','แมลงกัด ต่อย','Insect bited'),
	 ('J111101','การบาดเจ็บของข้อ','Joint injury'),
	 ('J111102','ข้อแพลง','Joint sprian'),
	 ('K111101','การบาดเจ็บของหัวเข่า','Knee injury'),
	 ('K111102','เข่าพลิก,แพลง','Knee sprian'),
	 ('L111101','แผลฉีกขาด','Lacerated wound'),
	 ('L111102','คอหอยอักเสบ','Laryngitis'),
	 ('M111103','ตึงกล้ามเนื้อ','Muscle strian');
INSERT INTO `_icd10` (`code`,`name_th`,`name_en`) VALUES
	 ('N111101','คลื่นไส้/อาเจียน','N/V'),
	 ('O111102','อุดตัน อุดกั้น','Obstruction'),
	 ('O111101','ปวด','Pain'),
	 ('R111101','ผื่น','Rash'),
	 ('S111101','รองเท้ากัด','Shoes puncher wound'),
	 ('S111102','การบาดเจ็บของเนื้อเยื่อ','Soft tissue injury'),
	 ('S111103','หนังตาอักเสบ','Style'),
	 ('S111104','เย็บแผล','Suture wound'),
	 ('T111101','ปวดตึง ศีรษะ','Tension Haedache'),
	 ('T111103','ทอนซิลอักเสบ','Tonsillitis');
INSERT INTO `_icd10` (`code`,`name_th`,`name_en`) VALUES
	 ('U111101','เลือดออกทางเดินอาหารส่วนต้น','UGIH'),
	 ('V111101','วิงเวียน','Vertigo'),
	 ('V111103','อาเจียน','Vomitting'),
	 ('W111101','อ่อนแรง','Weakness'),
	 ('W111102','แผล','Wound'),
	 ('0001','ไอ','cough'),
	 ('0002','ปวดขา',''),
	 ('0003','สัมผัสกับแรงเชิงกลวัตถุสิ่งของ',''),
	 ('0004','อาหารไม่ย่อย','Dyspepsia'),
	 ('0005','ภูมิแพ้','');
INSERT INTO `_icd10` (`code`,`name_th`,`name_en`) VALUES
	 ('0006','เส้นเลือดฝอยในตาแตก','Hyphema'),
	 ('0007','ปวดข้อมือ',''),
	 ('0008','ระคายเคือง คัน ตา',''),
	 ('0009','ปวดต้นคอ',' neck pain'),
	 ('0010','เจ็บคอ','Sore Throat'),
	 ('0011','กรามค้าง','lock jaw'),
	 ('0011','กรามค้าง','lock jaw'),
	 ('0012','ปวดหลัง','back pain'),
	 ('0013','เหงือกอักเสบ',''),
	 ('0014','คลื่นไส้ อาเจียน','');
INSERT INTO `_icd10` (`code`,`name_th`,`name_en`) VALUES
	 ('0015','ทอนซิลอักเสบ','tonsillitis'),
	 ('0016','คอหอยอักเสบ','phalyngitis'),
	 ('0017','ลมพิษ',''),
	 ('B353','เชื้อราที่เท้า',''),
	 ('','',''),
	 ('B351','เชื้อราที่เล็บ','Onychomycosis'),
	 ('L309','ผิวหนังอักเสบไม่ได้ระบุ',''),
	 ('B353','น้ำกัดเท้า','Tinea pedis'),
	 ('Z304','ฉีดยาคุมกำเนิด','Surveillance of contraceptive drugs'),
	 ('A111102','อุบัติเหตุ','Accident');
INSERT INTO `_icd10` (`code`,`name_th`,`name_en`) VALUES
	 ('A111106','แพ้','Allergy'),
	 ('A111108','หอบหืด','Asthma'),
	 ('C111103','หนาวสั่น','Chill'),
	 ('C111104','แผลเรื้อรัง','Chronic Wound'),
	 ('C111105','ไข้หวัด','Common Cold'),
	 ('C111107','บาดแผลฟกช้ำ','Contussion Wound'),
	 ('C111108','ไอ','Cough'),
	 ('C111109','แผลจากของมีคม','Cut wound'),
	 ('C111110','กระเพาะปัสสาวะอักเสบ','Cystitis'),
	 ('D111101','ผิวหนังอักเสบ จากการแพ้','Dermatitis');
INSERT INTO `_icd10` (`code`,`name_th`,`name_en`) VALUES
	 ('D111102','ท้องเสีย','Diarrhea'),
	 ('D111103','เคลื่อนหลุด','Dislocate'),
	 ('D111107','อาหารไม่ย่อย','Dyspepsia'),
	 ('E111102','ระคายเคืองตา','Eye irritated'),
	 ('F111104','อาหารเป็นพิษ','Food poinsoning'),
	 ('F111105','สิ่งแปลกปลอมในร่างกาย','Foreing body'),
	 ('F111106','แตก หัก','Fracture'),
	 ('G111101','กระเพาะอาหารอักเสบ','Gastitis'),
	 ('H111102','มีเลือดคั่ง','Hematoma'),
	 ('H111107','ความดันโลหิตสูง','Hypertension');
INSERT INTO `_icd10` (`code`,`name_th`,`name_en`) VALUES
	 ('I111101','แผลติดเชื้อ','Infected wound'),
	 ('I111102','แมลงกัด ต่อย','Insect bited'),
	 ('J111101','การบาดเจ็บของข้อ','Joint injury'),
	 ('J111102','ข้อแพลง','Joint sprian'),
	 ('K111101','การบาดเจ็บของหัวเข่า','Knee injury'),
	 ('K111102','เข่าพลิก,แพลง','Knee sprian'),
	 ('L111101','แผลฉีกขาด','Lacerated wound'),
	 ('L111102','คอหอยอักเสบ','Laryngitis'),
	 ('M111103','ตึงกล้ามเนื้อ','Muscle strian'),
	 ('N111101','คลื่นไส้/อาเจียน','N/V');
INSERT INTO `_icd10` (`code`,`name_th`,`name_en`) VALUES
	 ('O111102','อุดตัน อุดกั้น','Obstruction'),
	 ('O111101','ปวด','Pain'),
	 ('R111101','ผื่น','Rash'),
	 ('S111101','รองเท้ากัด','Shoes puncher wound'),
	 ('S111102','การบาดเจ็บของเนื้อเยื่อ','Soft tissue injury'),
	 ('S111103','หนังตาอักเสบ','Style'),
	 ('S111104','เย็บแผล','Suture wound'),
	 ('T111101','ปวดตึง ศีรษะ','Tension Haedache'),
	 ('T111103','ทอนซิลอักเสบ','Tonsillitis'),
	 ('U111101','เลือดออกทางเดินอาหารส่วนต้น','UGIH');
INSERT INTO `_icd10` (`code`,`name_th`,`name_en`) VALUES
	 ('V111101','วิงเวียน','Vertigo'),
	 ('V111103','อาเจียน','Vomitting'),
	 ('W111101','อ่อนแรง','Weakness'),
	 ('W111102','แผล','Wound'),
	 ('0017','กลาก เกลื้อน เชื้อราที่ผิวหนัง','Tinea circinato or ring worm'),
	 ('0018','กลาก เกลื้อน เชื้อราที่ผิวหนัง','Tinea circinato or ring worm');
INSERT INTO `_icd9` (`code`,`name_th`,`name_en`) VALUES
	 ('9963','CPR','Cardiac massage'),
	 ('8604','ระบายของเหลว,น้ำ','Drainage of skin and subcutaneous tissue'),
	 ('10013','การปฐมพยาบาลเบื้องต้น','FIRST AID'),
	 ('9820','คีบสิ่งแปลกปลอม ออกจากร่างกาย','Removal of foreign body, not otherwise specified'),
	 ('9789','ตัดไหม','Removal of other therapeutic device'),
	 ('9357','ล้างแผล','Dressing of wound'),
	 ('10017','ทำแผลขนาดกลาง','MILD-MODERATE-SEVERE'),
	 ('10018','ทำแผลขนาดใหญ่','MAJOR DRESSING'),
	 ('10019','นวด','MASSAGE'),
	 ('10020','ประคบเย็น','COOL COMPRESS');
INSERT INTO `_icd9` (`code`,`name_th`,`name_en`) VALUES
	 ('10021','ประคบร้อน','HOT COMPRESS'),
	 ('9653','ล้างจมูก','Irrigation of nasal passages'),
	 ('9651','ล้างตา','Irrigation of eye'),
	 ('9652','ล้างหู เอาสิ่งแปลกปลอมออกจากหู','Removal of cerumen from ear'),
	 ('9353','ใส่เฝือก','Application of limb cast'),
	 ('10026','ห้ามเลือด','STOP BLEEDING'),
	 ('9929','ฉีดยา','Injection or infusion of other therapeutic or prophylactic substance'),
	 ('8659','เย็บแผล','Suture of laceration of skin'),
	 ('8627','ถอดเล็บ','Removal of nail, nailbed or nailfold'),
	 ('0001','ประคบร้อน','');
INSERT INTO `_icd9` (`code`,`name_th`,`name_en`) VALUES
	 ('0002','ประคบเย็น',''),
	 ('01','พันเคล็ด',''),
	 ('0003','พันเคล็ด',''),
	 ('0004','นอนพัก','rest'),
	 ('0005','วัดความดันโลหิต','');
INSERT INTO `_medsup` (`catagory`,`code`,`name`,`price`,`unit`,`unitf`,`prices`,`units`,`description`) VALUES
	 ('MATERIAL','1','BASIC DRESSING SET',13.4,'ชุด','12','160','box',''),
	 ('MATERIAL','2','COLD HOT PACK',0.0,'piece','1','0','box',''),
	 ('MATERIAL','3','CONFORM 2"',0.0,'ม้วน','12','0','box',''),
	 ('MATERIAL','4','CONFORM 3" ',0.0,'ม้วน','12','0','box',''),
	 ('MATERIAL','5','CONFORM 4"',0.0,'ม้วน','12','0','box',''),
	 ('MATERIAL','6','COOLER 4 lite',0.0,'piece','0','0','box',''),
	 ('MATERIAL','7','COOLER 9 lite',0.0,'piece','0','0','box',''),
	 ('MATERIAL','8','COTTON BALL',0.0,'ห่อ','0','0','box',''),
	 ('MATERIAL','9','COTTON STICK LONG S5',0.0,'pack','0','0','box',''),
	 ('MATERIAL','10','COTTON STICK LONG S10 ',0.0,'pack','0','0','box','');
INSERT INTO `_medsup` (`catagory`,`code`,`name`,`price`,`unit`,`unitf`,`prices`,`units`,`description`) VALUES
	 ('MATERIAL','11','COTTON STICK LONG M5 ',0.0,'pack','0','0','box',''),
	 ('MATERIAL','12','COTTON STICK LONG M10',0.0,'pack','0','0','box',''),
	 ('MATERIAL','13','COTTON STICK LONG L5',0.0,'pack','0','0','box',''),
	 ('MATERIAL','14','COTTON STICK LONG L10',0.0,'pack','0','0','box',''),
	 ('MATERIAL','15','DTX',0.0,'ชิ้น','0','450','box',''),
	 ('MATERIAL','16','ELASTIC BANDAGE 2"',0.0,'ม้วน','12','0','box',''),
	 ('MATERIAL','17','ELASTIC BANDAGE 3"',15.5,'ม้วน','12','185','box',''),
	 ('MATERIAL','18','ELASTIC BANDAGE 4"',20.9,'ม้วน','12','250','box',''),
	 ('MATERIAL','19','ELECTIRC PACK',2200.0,'piece','1','2200','box',''),
	 ('MATERIAL','20','NEOBUN GEL COOL',0.0,'box','0','0','box','');
INSERT INTO `_medsup` (`catagory`,`code`,`name`,`price`,`unit`,`unitf`,`prices`,`units`,`description`) VALUES
	 ('MATERIAL','21','EYE PAD',0.0,'ชิ้น','0','0','box',''),
	 ('MATERIAL','22','FIRST AID KIT',0.0,'kit','0','0','box',''),
	 ('MATERIAL','23','FIRST AID BAG S',0.0,'kit','0','0','box',''),
	 ('MATERIAL','24','FIRST AID BAG L',0.0,'kit','0','0','box',''),
	 ('MATERIAL','25','SOFT COLLAR S',0.0,'piece','0','0','box',''),
	 ('MATERIAL','26','SOFT COLLAR M',0.0,'piece','0','0','box',''),
	 ('MATERIAL','27','SOFT COLLAR L',0.0,'piece','0','0','bott',''),
	 ('MATERIAL','28','GAUZE 2" × 2"',1.6,'ชิ้น','100','155','box',''),
	 ('MATERIAL','29','GAUZE 3" × 3"',2.3,'ชิ้น','100','225','box',''),
	 ('MATERIAL','30','GAUZE DRAIN',0.0,'box','0','420','box','');
INSERT INTO `_medsup` (`catagory`,`code`,`name`,`price`,`unit`,`unitf`,`prices`,`units`,`description`) VALUES
	 ('MATERIAL','31','GLOVE M disposible',0.0,'box','1','0','box',''),
	 ('MATERIAL','32','GLOVE S disposible',0.0,'box','1','0','box',''),
	 ('MATERIAL','33','GLOVE STERILE 6 1/2',0.0,'box','0','0','box',''),
	 ('MATERIAL','34','GLOVE STERILE 7',0.0,'box','0','0','box',''),
	 ('MATERIAL','35','IV CATH NO.20',0.0,'piece','1','0','box',''),
	 ('MATERIAL','36','IV CATH NO.22',0.0,'piece','1','0','box',''),
	 ('MATERIAL','37','IV SET',0.0,'piece','50','0','box',''),
	 ('MATERIAL','38','MASK DISPOSIBLE',0.0,'ชิ้น','50','0','box',''),
	 ('MATERIAL','39','MASK N. 95',0.0,'box','0','0','pot',''),
	 ('MATERIAL','40','MASK C BAG',0.0,'piece','0','0','box','');
INSERT INTO `_medsup` (`catagory`,`code`,`name`,`price`,`unit`,`unitf`,`prices`,`units`,`description`) VALUES
	 ('MATERIAL','41','หน้ากากพ่นยา',0.0,'piece','0','0','pot',''),
	 ('MATERIAL','42','MICROPORE 1/2''',9.5,'box','12','114','box',''),
	 ('MATERIAL','43','MICROPORE 1''',17.8,'box','12','213','box',''),
	 ('MATERIAL','44','NEEDLE NO. 20',0.0,'box','100','0','box',''),
	 ('MATERIAL','45','NEEDLE NO. 24',0.0,'box','100','0','box',''),
	 ('MATERIAL','46','NEEDLE NO. 26',0.0,'box','100','0','box',''),
	 ('MATERIAL','47','NEOFILM',0.0,'box','10','0','box',''),
	 ('MATERIAL','48','NEOFIX',0.0,'box','1','0','pot500',''),
	 ('MATERIAL','49','NE0TAPE 1/2"',0.0,'tube','0','0','pot1000',''),
	 ('MATERIAL','50','NE0TAPE 1"',0.0,'tube','0','0','box','');
INSERT INTO `_medsup` (`catagory`,`code`,`name`,`price`,`unit`,`unitf`,`prices`,`units`,`description`) VALUES
	 ('MATERIAL','51','NE0TAPE 2"',0.0,'tube','0','0','pot1000',''),
	 ('MATERIAL','52','NEOPRESS RED ',0.0,'pack3','0','0','pot1000',''),
	 ('MATERIAL','53','NEOPRESS YELLOW ',0.0,'pack3','0','0','box',''),
	 ('MATERIAL','54','NEOPRESS BLUE ',0.0,'pack3','0','0','box',''),
	 ('MATERIAL','55','NEO COMBAT ',0.0,'box','0','0','pot1000',''),
	 ('MATERIAL','56','PLASTER ผ้า',0.0,'ชิ้น','100','0','box',''),
	 ('MATERIAL','57','PLASTER PLASTIC',0.0,'ชิ้น','100','0','box',''),
	 ('MATERIAL','58','PRESSNET 0.5',0.0,'box','0','0','box',''),
	 ('MATERIAL','59','PRESSNET 1',0.0,'box','0','0','box',''),
	 ('MATERIAL','60','PRESSNET 5',0.0,'box','0','0','pot1000','');
INSERT INTO `_medsup` (`catagory`,`code`,`name`,`price`,`unit`,`unitf`,`prices`,`units`,`description`) VALUES
	 ('MATERIAL','61','STERILE STRIP',0.0,'box','0','0','doz',''),
	 ('MATERIAL','62','STETHOSCOPE',0.0,'piece','0','0','box20',''),
	 ('MATERIAL','63','SPHYGMOMANOMETER ',0.0,'piece','0','0','doz',''),
	 ('MATERIAL','64','SYRINGE 0.5 ML',0.0,'box','100','0','box50',''),
	 ('MATERIAL','65','SYRINGE 3 ML',0.0,'box','100','0','box20',''),
	 ('MATERIAL','66','SYRINGE 5 ML',0.0,'box','100','0','doz',''),
	 ('MATERIAL','67','SYRINGE 10 ML',0.0,'box','100','0','doz',''),
	 ('MATERIAL','68','SYRINGE 20 ML',0.0,'box','50','0','doz',''),
	 ('MATERIAL','69','SOFRA TOOLEY',0.0,'box','10','0','doz',''),
	 ('MATERIAL','70','TERMOMITER',0.0,'piece','0','0','doz','');
INSERT INTO `_medsup` (`catagory`,`code`,`name`,`price`,`unit`,`unitf`,`prices`,`units`,`description`) VALUES
	 ('MATERIAL','71','TRANSPORE 1/2''',0.0,'box','12','0','box',''),
	 ('MATERIAL','72','TRANSPORE 1''',0.0,'box','12','0','doz',''),
	 ('MATERIAL','73','TRANSPORE 4''',0.0,'box','0','0','tube',''),
	 ('MATERIAL','74','TONGUE DEPRESSOR',0.0,'box','0','0','box',''),
	 ('MATERIAL','75','TUBRIGRIP Wrist S',0.0,'box','0','0','doz',''),
	 ('MATERIAL','76','TUBRIGRIP Wrist M',0.0,'piece','0','0','tube10',''),
	 ('MATERIAL','77','TUBRIGRIP Wrist L',0.0,'piece','0','0','doz',''),
	 ('MATERIAL','78','TUBRIGRIP Elbow S',0.0,'box','0','0','tube/d',''),
	 ('MATERIAL','79','TUBRIGRIP Elbow M',0.0,'piece','0','0','box',''),
	 ('MATERIAL','80','TUBRIGRIP Elbow L',0.0,'piece','0','0','doz','');
INSERT INTO `_medsup` (`catagory`,`code`,`name`,`price`,`unit`,`unitf`,`prices`,`units`,`description`) VALUES
	 ('MATERIAL','81','TUBRIGRIP Knee S',0.0,'piece','0','0','bott',''),
	 ('MATERIAL','82','TUBRIGRIP Knee M',0.0,'piece','0','0','tube',''),
	 ('MATERIAL','83','TUBRIGRIP Knee L',0.0,'piece','0','0','doz',''),
	 ('MATERIAL','84','KNEE SUPPORT S',0.0,'piece','0','0','box',''),
	 ('MATERIAL','85','KNEE SUPPORT M',0.0,'piece','0','0','box',''),
	 ('MATERIAL','86','KNEE SUPPORT L',0.0,'piece','0','0','doz',''),
	 ('MATERIAL','87','KNEE SUPPORT XL',0.0,'piece','0','0','doz',''),
	 ('MATERIAL','88','ANKLE BRACE OPENEND S',0.0,'piece','0','0','doz',''),
	 ('MATERIAL','89','ANKLE BRACE OPENEND M',0.0,'piece','0','0','bott',''),
	 ('MATERIAL','90','ANKLE BRACE OPENEND L',0.0,'piece','0','0','bott','');
INSERT INTO `_medsup` (`catagory`,`code`,`name`,`price`,`unit`,`unitf`,`prices`,`units`,`description`) VALUES
	 ('MATERIAL','91','ANKLE BRACE OPENEND XL',0.0,'piece','0','0','bott',''),
	 ('MATERIAL','92','ANKLE SUPPORT S',0.0,'piece','0','0','box',''),
	 ('MATERIAL','93','ANKLE SUPPORT M',0.0,'piece','0','0','box60',''),
	 ('MATERIAL','94','ANKLE SUPPORT L',0.0,'piece','0','0','bott',''),
	 ('MATERIAL','95','ANKLE SUPPORT XL',0.0,'piece','0','0','bott',''),
	 ('MATERIAL','96','indicator tape',0.0,'piece','0','0','bott',''),
	 ('เวชภัณฑ์ทำความสะอาด','97','DETTOL',0.0,'หน่วย','0','0','bott',''),
	 ('เวชภัณฑ์ทำความสะอาด','98','DETERGENT',0.0,'หน่วย','0','0','box24',''),
	 ('เวชภัณฑ์ทำความสะอาด','99','HIBI SCRUB',0.0,'หน่วย','0','0','box',''),
	 ('เวชภัณฑ์ทำความสะอาด','100','น้ำยาฆ่าเชื้อ',0.0,'หน่วย','0','0','box12','');
INSERT INTO `_medsup` (`catagory`,`code`,`name`,`price`,`unit`,`unitf`,`prices`,`units`,`description`) VALUES
	 ('เวชภัณฑ์ทำความสะอาด','101','สเปร์ยฆ่าเชื้อ',0.0,'หน่วย','0','0','bott',''),
	 ('-','102','GLOVE L disposible',0.0,'box','1','0','amp',''),
	 ('-','103','PREG TEST',0.0,'pack10','0','0','amp',''),
	 ('-','104','NEEDLE NO. 25',0.0,'box','100','0','bott',''),
	 ('-','105','NSS IRRIGATION 500 ML',0.0,'หน่วย','0','0','amp',''),
	 ('','106','ARM SLING S',0.0,'piece','0','0','piece',''),
	 ('','107','ARM SLING M',0.0,'piece','0','0','piece',''),
	 ('','108','ARM SLING L',0.0,'piece','0','0','piece',''),
	 ('','109','ARM SLING XL',0.0,'piece','0','0','piece',''),
	 ('','110','ไม้เท้าค้ำยันรักแร้ 48',0.0,'คู่','0','0','คู่','');
INSERT INTO `_medsup` (`catagory`,`code`,`name`,`price`,`unit`,`unitf`,`prices`,`units`,`description`) VALUES
	 ('','111','ไม้เท้าค้ำยันรักแร้ 50',0.0,'คู่','0','0','คู่',''),
	 ('','112','ไม้เท้าค้ำยันรักแร้ 52',0.0,'คู่','0','0','คู่',''),
	 ('','113','ไม้เท้าค้ำยันรักแร้ 54',0.0,'คู่','0','0','คู่',''),
	 ('','114','ไม้เท้าค้ำยันรักแร้ 56',0.0,'คู่','0','0','คู่',''),
	 ('','115','ผ้าเย็นขนหนู',0.0,'ชิ้น','30','0','pack',''),
	 ('','116','น้ำมันมวย 30 มล.',0.0,'ขวด','','','โหล',''),
	 ('','117','แผ่นฟิล์มปิดแผลกันน้ำ10*12',0.0,'ชิ้น','','','box',''),
	 ('','118','แผ่นฟิล์มปิดแผลกันน้ำ6*7',0.0,'ชิ้น','','','box',''),
	 ('','','ฟ้าทะลายโจร',0.0,'','','','เม็ด','');
INSERT INTO `_ncd` (`name`) VALUES
	 ('โรคเบาหวาน'),
	 ('โรคหลอดเลือดสมองและหัวใจ '),
	 ('โรคถุงลมโป่งพอง '),
	 ('โรคมะเร็ง '),
	 ('โรคความดันโลหิตสูง '),
	 ('โรคอ้วนลงพุง '),
	 ('ไขมันในเลือดสูง'),
	 ('ภาวะน้ำตาลในเลือดต่ำ'),
	 ('หอบหืด'),
	 ('ภูมิแพ้');
INSERT INTO `_ncd` (`name`) VALUES
	 ('ไมเกรน'),
	 ('กระดูกเสื่อม,พรุน'),
	 ('ต่อมลูกหมากโต'),
	 ('ไทรอยด์'),
	 ('พาร์กินสัน'),
	 ('สะเก็ดเงิน'),
	 ('โรคหัวใจ'),
	 ('ธาลัสซีเมีย'),
	 ('โลหิตจาง'),
	 ('ซึมเศร้า');
INSERT INTO `_ncd` (`name`) VALUES
	 ('ไตวาย'),
	 ('รูมาตอยด์'),
	 ('เกาต์'),
	 ('อัมพฤกษ์'),
	 ('G6PD'),
	 ('ตับอักเสบ'),
	 ('ตับแข็ง'),
	 ('ตาบอดสี'),
	 ('ปอดติดเชื้อ TB ,วัณโรค'),
	 ('ต้อหิน');
INSERT INTO `_ncd` (`name`) VALUES
	 ('ต้อกระจก'),
	 ('โรคลมชัก'),
	 ('อื่นๆ'),
	 ('ไม่มี'),
	 (''),
	 ('xxxx');
INSERT INTO `_org` (`name`,`code`) VALUES
	 ('กองกลาง','1001'),
	 ('กองการเจ้าหน้าที่','1002'),
	 ('กองกิจการนักศึกษา','1003'),
	 ('กองคลัง','1004'),
	 ('กองบริการการศึกษา','1005'),
	 ('กองแผนงาน','1006'),
	 ('กองงานศูนย์รังสิต','1007'),
	 ('กองส่งเสริมมาตรฐานและประกันคุณภาพ','1008'),
	 ('กองวิเทศสัมพันธ์','1009'),
	 ('สำนักหอสมุด','1010');
INSERT INTO `_org` (`name`,`code`) VALUES
	 ('สำนักเสริมศึกษาและบริการสังคม','1011'),
	 ('สำนักทะเบียนและประมวลผล','1012'),
	 ('สำนักบัณฑิตอาสาสมัคร','1013'),
	 ('สถาบันไทยคดีศึกษา','1014'),
	 ('สถาบันประมวลข้อมูลเพื่อการศึกษาและการพัฒนา','1015'),
	 ('สถาบันทรัพยากรมนุษย์','1016'),
	 ('สถาบันเอเชียตะวันออกศึกษา','1017'),
	 ('สถาบันภาษา','1018'),
	 ('สถาบันวิจัยและให้คำปรึกษาฯ','1019'),
	 ('สถาบันสัญญา ธรรมศักดิ์ เพื่อประชาธิปไตย','1020');
INSERT INTO `_org` (`name`,`code`) VALUES
	 ('ศูนย์อินเดียศึกษา','1021'),
	 ('ศูนย์อาเซียนศึกษา','1022'),
	 ('ศูนย์ออสเตรเลียศึกษา','1023'),
	 ('ศูนย์ศึกษารัสเซียและเครือรัฐเอกราช','1024'),
	 ('ศูนย์ศึกษาความร่วมมือระหว่างประเทศแห่งมหาวิทยาลัยธรรมศาสตร์','1025'),
	 ('ศูนย์ประสานราชการใสสะอาด','1026'),
	 ('LeTec ศูนย์การเรียนรู้ด้านกฎหมาย','1027'),
	 ('สำนักงานวิเทศสัมพันธ์','1028'),
	 ('สำนักงานตรวจสอบภายใน','1029'),
	 ('สำนักงานอาคารสถานที่ศูนย์รังสิต','1030');
INSERT INTO `_org` (`name`,`code`) VALUES
	 ('สำนักงานนิติการ','1031'),
	 ('สำนักงานประสานศูนย์การศึกษาภูมิภาค','1032'),
	 ('สำนักงานบริหารการวิจัย','1033'),
	 ('สำนักงานบริหารศูนย์ลำปาง','1034'),
	 ('โครงการสตรีและเยาวชนศึกษา','1035'),
	 ('โครงการหอจดหมายเหตุฯ','1036'),
	 ('โรงพยาบาลธรรมศาสตร์เฉลิมพระเกียรติ','1037'),
	 ('ศูนย์หนังสือ','1038'),
	 ('ศูนย์อินเดียศึกษา','1039'),
	 ('ศูนย์บริการการกีฬา','1040');
INSERT INTO `_org` (`name`,`code`) VALUES
	 ('ศูนย์ศึกษาความร่วมมือระหว่างประเทศ แห่งมธ.','1041'),
	 ('ศูนย์ประสานข้าราชการใสสะอาด','1042'),
	 ('ศูนย์ประชุมธรรมศาสตร์ รังสิต','1043'),
	 ('สภามหาวิทยาลัย','1044'),
	 ('สภาข้าราชการ','1045'),
	 ('สภาอาจารย์','1046'),
	 ('สหกรณ์ออมทรัพย์','1047'),
	 ('ธรรมศาสตร์สโมสร','1048'),
	 ('สำนักพิมพ์','1049'),
	 ('โรงพิมพ์','1050');
INSERT INTO `_org` (`name`,`code`) VALUES
	 ('สำนักงานจัดการทรัพย์สิน','1051'),
	 ('สำนักงานศิษย์เก่าสัมพันธ์','1052'),
	 ('สำนักทรัพย์สินทางปัญญาและบ่มเพาะวิสาหกิจ','1053'),
	 ('คณะนิติศาสตร์','1054'),
	 ('คณะพาณิชยศาสตร์และการบัญชี','1055'),
	 ('คณะรัฐศาสตร์','1056'),
	 ('คณะเศรษฐศาสตร์','1057'),
	 ('คณะสังคมสงเคราะห์ศาสตร์','1058'),
	 ('คณะสังคมวิทยาและมานุษยวิทยา','1059'),
	 ('คณะศิลปศาสตร์','1060');
INSERT INTO `_org` (`name`,`code`) VALUES
	 ('คณะวารสารศาสตร์และสื่อสารมวลชน','1061'),
	 ('คณะวิทยาศาสตร์และเทคโนโลยี','1062'),
	 ('คณะวิศวกรรมศาสตร์','1063'),
	 ('สถาบันเทคโนโลยีนานาชาติสิรินธร','1064'),
	 ('คณะสถาปัตยกรรมและการผังเมือง','1065'),
	 ('คณะศิลปกรรมศาสตร์','1066'),
	 ('คณะแพทยศาสตร์','1067'),
	 ('คณะสหเวชศาสตร์','1068'),
	 ('คณะทันตแพทยศาสตร์','1069'),
	 ('คณะพยาบาลศาสตร์','1070');
INSERT INTO `_org` (`name`,`code`) VALUES
	 ('คณะสาธารณสุขศาสตร์','1071'),
	 ('คณะเภสัชศาสตร์','1072'),
	 ('คณะวิทยาการเรียนรู้และศึกษาศาสตร์','1073'),
	 ('สำนักบัณฑิตอาสาสมัคร','1074'),
	 ('สถาบันภาษา','1075'),
	 ('วิทยาลัยนวัตกรรม','1076'),
	 ('วิทยาลัยสหวิทยาการ','1077'),
	 ('วิทยาลัยนานาชาติ ปรีดี พนมยงค์','1078'),
	 ('วิทยาลัยแพทยศาสตร์นานาชาติจุฬาภรณ์','1079'),
	 ('วิทยาลัยโลกคดีศึกษา','1080');
INSERT INTO `_org` (`name`,`code`) VALUES
	 ('ศูนย์สัตว์ทดลอง','1081'),
	 ('สำนักงานอธิการบดี','1082'),
	 ('สหกรณ์ออมทรัพย์มธ','1083'),
	 ('สหกรณ์ออมทรัพย์มธ','1083'),
	 ('ศูนย์หนังสือ มธ','1084'),
	 ('กองนิติการ','1085'),
	 ('อื่นๆ(บุคคลภายนอก)','1086'),
	 ('กองบริหารงานวิจัย','1087'),
	 ('กองบริหารศูนย์ท่าพระจันทร์','89'),
	 ('หน่วยรักษาความสงบ','01');
INSERT INTO `_org` (`name`,`code`) VALUES
	 ('xxxx','01'),
	 ('xxxx',''),
	 ('','');
INSERT INTO `_stf` (`name`) VALUES
	 ('นายแพทย์/แพทย์หญิง'),
	 ('พรทิพย์  ธีระกาญจน์ (พยาบาล)'),
	 ('ทาริกา  คำกิ่ง (พยาบาล)'),
	 ('วัชราภา  บุญชัยยุทธศักดิ์ (พยาบาล)'),
	 ('เปรมา  ศรีพรหม (พยาบาล)'),
	 ('อนันตพร  เนียมปาน (พยาบาล)'),
	 ('พยาบาล'),
	 ('สุภา  แสงฤทธิ์เดช (พยาบาล)'),
	 ('ทัศนีย์  สาวาโย (พยาบาล)'),
	 ('พรทิพย์ มีหมู่ (พยาบาล)');
INSERT INTO `_stf` (`name`) VALUES
	 ('ชุณห์พิมาณ  บุญมา (พยาบาล)'),
	 ('สุรางรัตน์  วรีวงศ์ (พยาบาล)'),
	 ('ชุติมล  อยู่เจริญ (พยาบาล)'),
	 ('พนิดา  ศรีเรือง (พยาบาล)'),
	 ('วงศ์มณี  วัดพ่วงงา (พยาบาล)'),
	 ('ขวัญสุดา  วิญคาม (พยาบาล)'),
	 ('วันวิสา  พันธสำราญสุข (พยาบาล)'),
	 ('นฤมล  ฉายาชวลิต (พยาบาล)'),
	 ('อัมพวัน  แจ้งคำขำ (พยาบาล)'),
	 ('วรางคณา  เลี้ยงตน (พยาบาล)');
INSERT INTO `_stf` (`name`) VALUES
	 ('ปานไพลิน  สมใจเพ็ง (พยาบาล)'),
	 ('สายรุ้ง พิมพ์ศรี (พยาบาล)'),
	 ('ศิริพร คิ้วสถาพร (พยาบาล)'),
	 ('พยาบาลพาร์ทไทม์'),
	 ('วรรณพร พลนิกร (พยาบาล)');
INSERT INTO `_stock` (`name`) VALUES
	 ('คลังใหญ่'),
	 ('ตึกอธิการบดี ชั้น 1'),
	 ('ตึก SC ชั้น 1'),
	 ('ท่าพระจันทร์'),
	 ('จัดยาชุดปฐมพยาบาล'),
	 ('บริการสังคม');
INSERT INTO `_usg` (`name`,`description`) VALUES
	 ('ยาทาน','รับประทานครั้งละ 1 เม็ด, วันละ 3 ครั้ง,หลังอาหาร เช้า- กลางวัน- เย็น '),
	 ('ยาทาน','รับประทานครั้งละ x ช้อนชา, วันละ x ครั้ง, ก่อนนอน'),
	 ('ยาทาน','รับประทานครั้งละ x ช้อนชาครึ่ง ทุก x ชั่วโมง เวลาปวดหรือมีไข้'),
	 ('ยาทาน','รับประทานครั้งละ 2 เม็ด วันละ 2 ครั้ง หลังอาหาร เช้า-เย็น'),
	 ('ยาทาน','อมครั้งละ 1 เม็ด ทุก 1-2 ชม. เวลามีอาการเจ็บคอ'),
	 ('ยาทาน','จิบเวลาไอ'),
	 ('ยาหยอดตา','หยอดตา ครั้งละ 1-2 หยด วันละ 1 ครั้ง เช้า'),
	 ('ยาหยอดตา','หยอดตา ครั้งละ 1-2 หยด วันละ 1 ครั้ง ก่อนนอน'),
	 ('ยาหยอดตา','หยอดตาข้างที่เป็นครั้งละ 1-2 หยด ทุก x ชั่วโมง'),
	 ('ยาหยอดตา','หยอดตาทั้ง 2 ข้าง ครั้งละ 1-2 หยด วันละ 4 ครั้ง เช้า-กลางวัน-เย็น-ก่อนนอน');
INSERT INTO `_usg` (`name`,`description`) VALUES
	 ('ยาหยอดหู','หยอดหู ครั้งละ 1-2 หยด วันละ 2 ครั้ง เช้า-เย็น'),
	 ('ยาหยอดหู','หยอดหู ครั้งละ 1-2 หยด วันละ 3 ครั้ง เช้า-กลางวัน-เย็น'),
	 ('ยาหยอดหู','หยอดหูข้างที่เป็นครั้งละ 1-2 หยด ทุก x ชั่วโมง'),
	 ('ยาหยอดหู','หยอดหูทั้ง 2 ข้าง ครั้งละ 1-2 หยด วันละ 4 ครั้ง เช้า-กลางวัน-เย็น-ก่อนนอน'),
	 ('ยาป้ายตา','ป้ายตา วันละ 3 ครั้ง เช้า-กลางวัน-เย็น'),
	 ('ยาป้ายตา','ป้ายตา วันละ 4 ครั้ง เช้า-กลางวัน-เย็น-ก่อนนอน'),
	 ('ยาทา','ทาบางๆเฉพาะที่ วันละ 2 ครั้ง เช้า-เย็น'),
	 ('ยาทา','ทาบางๆเฉพาะที่ วันละ 3 ครั้ง เช้า-กลางวัน-เย็น'),
	 ('ยาทา','ป้ายแผลในปาก วันละ 4 ครั้ง เช้า-กลางวัน-เย็น-ก่อนนอน'),
	 ('ยาสูดพ่น','พ่นยา 2 ที วันละ 2 ครั้ง เช้า-เย็น');
INSERT INTO `_usg` (`name`,`description`) VALUES
	 ('ยาสูดพ่น','พ่นยา 1 ที โดยกดก้นขวดยาลงจนสุด 1 ครั้ง พร้อมสูดยาทุก x ชั่วโมง เวลามีอาการหอบ'),
	 ('ยาพ่นจมูก','พ่นจมูก 1 ข้าง วันละ 2 เวลา เช้า-เย็น'),
	 ('ยาพ่นจมูก','พ่นจมูก 2 ข้าง ข้างละ x ครั้ง วันละ 1 ครั้ง เช้า'),
	 ('ยาพ่นจมูก','พ่นจมูก 2 ข้าง ข้างละ x ครั้ง วันละ 2 ครั้ง เช้า-เย็น'),
	 ('ยาเหน็บทวาร','เหน็บทวาร ครั้งละ 1 เม็ด วันละ 1 ครั้งก่อนนอน'),
	 ('ยาเหน็บทวาร','เหน็บทวาร ครั้งละ 1 เม็ด วันละ 2 ครั้ง เช้า-ก่อนนอน'),
	 ('ยาเหน็บช่องคลอด','สอดช่องคลอด ครั้งละ x เม็ด วันละ 1 ครั้งก่อนนอน'),
	 ('ยาฉีด','ฉีดเข้ากล้าม x cc'),
	 ('ยาฉีด','ฉีดเข้ากล้าม ครั้งละ x amp./vial'),
	 ('ยาฉีด','ฉีดเข้าเส้น (iv) ครั้งละ x amp');
INSERT INTO `_usg` (`name`,`description`) VALUES
	 ('ยาทาน','รับประทานครั้งละ 1 เม็ด วันละ 3 ครั้ง หลังอาหารทันที เช้า-กลางวัน-เย็น'),
	 ('ยาทาน','รับประทานครั้งละ 1-2 เม็ด ทุก4-6 ชั่วโมง เวลาปวด หรือมีไข้'),
	 ('ยาทา','กกกก');
